site_name: DotEnv User Documentation
site_url: https://sitename.example
nav:
    - Home: index.md
    - Set-up: Dotenv-Configuration.md
    - Port usage: port.md
    - Secrets usage: secrets.md
    - gitignore: gitignore.md
    - Troubleshooting: troubleshooting.md
    - Glossary: glossary.md

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  features:
    - content.tabs.link

  logo: assets/image.png
  favicon: assets/image.png
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences


extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/


copyright: Copyright &copy; 2025 Lam Thai






